lib/fly_web/router.ex
defmodule FlyWeb.Router do
  use FlyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {FlyWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :authenticated do
    plug FlyWeb.Plugs.RequireSession, "/"
  end

  scope "/", FlyWeb do
    pipe_through [:browser, :authenticated]

    get "/", Plugs.Redirect, to: "/apps"

    live_session :authenticated, on_mount: FlyWeb.Plugs.RequireSession do
      live "/apps", AppLive.Index, :index
      live "/billing", AppLive.Billing, :index
    end
  end

  scope "/", FlyWeb do
    pipe_through :browser

    delete "/session/destroy", SessionController, :delete, as: "delete_session"
    resources "/session", SessionController, only: [:new, :create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", FlyWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: FlyWeb.Telemetry
    end
  end
end

lib/fly_web/views/layout_view.ex
defmodule FlyWeb.LayoutView do
  use FlyWeb, :view

  alias FlyWeb.Components.{HeaderLinks, AppList, TabSelector, VolumeList, SideApp}
end

lib/fly_web/templates/layout/app.html.heex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/fly_web/templates/layout/fonts.js.eex
/**
  * LoadFont 0.0.3
  * A font loader that leverages LocalStorage
  * @author Adam Beres-Deak (@bdadam) & Kyle Foster (@hkfoster)
  * @source https://github.com/bdadam/OptimizedWebfontLoading
  * @license MIT
  **/
var localStorageAvailable=function(e){var t="test",a=window.localStorage;try{return a.setItem(t,"1"),a.removeItem(t),!0}catch(e){return!1}}(),loadFont=function(e,t,a){if(localStorageAvailable){var n={};try{n=localStorage||{}}catch(e){}var o="x-font-"+e,l=o+"url",r=o+"css",s=n[l],c=n[r],u=s===t,d=document.createElement("style");if(d.rel="stylesheet",document.head.appendChild(d),c&&u)d.textContent=c;else{var i=new XMLHttpRequest;i.open("GET",t),i.onload=function(){i.status>=200&&i.status<400&&(n[l]=t,n[r]=i.responseText,a||(d.textContent=i.responseText))},i.send()}}};

lib/fly_web/templates/layout/live.html.heex
<div class="h-full min-h-full flex flex-col">
  <div class="bg-gray-800 pb-32">
    <nav class="bg-gray-800">
      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <div class="border-b border-gray-700">
          <div class="flex items-center justify-between h-16 px-4 sm:px-0">
            <div class="flex items-center">
              <div class="flex-shrink-0">
                <img class="h-12 w-12 rounded-full" src={Routes.static_path(@socket, "/images/fly-logo.png")} alt="Workflow">
              </div>
              <div class="hidden md:block">
                <div class="ml-2 flex items-baseline space-x-4">
                  <HeaderLinks.render 
                    currentUrl={@__path__}
                    links={[
                    {"Dashboard", Routes.app_index_path(@socket, :index), ~r/apps/},
                    {"Billing", Routes.app_billing_path(@socket, :index), ~r/billing/}
                    ]} />
                </div>
              </div>
            </div>
            <div class="hidden md:flex items-center justify-end md:flex-1 lg:w-0">
              <%= link to: Routes.delete_session_path(@socket, :delete), method: :delete,
                class: "whitespace-nowrap text-base font-medium text-gray-500 hover:text-gray-700" do %>
                Sign Out
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>
  </div>
  <%= @inner_content %>
</div>
<FlyWeb.Components.flash_alert flash={@flash} type={:success} />
<FlyWeb.Components.flash_alert flash={@flash} type={:info} />
<FlyWeb.Components.flash_alert flash={@flash} type={:warn} />
<FlyWeb.Components.flash_alert flash={@flash} type={:error} />

lib/fly_web/templates/layout/root.html.heex
<!doctype html>
<html lang="en-US" class="h-full">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Fly", suffix: "" %>

    <link rel="shortcut icon" type="image/x-icon" href={Routes.static_path(@conn, "/ui/images/favicon/favicon.ico")}>
    <link rel="apple-touch-icon" sizes="180x180" href={Routes.static_path(@conn, "/ui/images/favicon/apple-touch-icon.png")}>
    <link rel="icon" type="image/png" sizes="32x32" href={Routes.static_path(@conn, "/ui/images/favicon/favicon-32x32.png")}>
    <link rel="icon" type="image/png" sizes="16x16" href={Routes.static_path(@conn, "/ui/images/favicon/favicon-16x16.png")}>
    <link rel="mask-icon" href={Routes.static_path(@conn, "/ui/images/favicon/safari-pinned-tab.svg")} color="#4d7cfe">
    <meta name="msapplication-TileColor" content="#4d7cfe">
    <meta name="theme-color" content="#ffffff">

    <script>
      <%= render "fonts.js" %>
      loadFont("fly-", "<%= Routes.static_path(@conn, "/css/fonts.css") %>")
    </script>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/css/app.css")} />
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/js/app.js")}></script>
  </head>

  <body class="relative w-full h-full text-gray-500 antialiased">

    <%= @inner_content %>

  </body>
</html>